config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'welcome#index'

  resources :jobs

end

app/models/job.rb
class Job < ActiveRecord::Base
  validates :company_name, :link, :job_title, :location, :status, :note, :contact_email, :intrigue_level, presence: true
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :jobs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    jobs_path
  end

  def after_sign_out_path_for(resource_or_scope)
    root_path
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :authenticate_user!

  def index
    @jobs = Job.all.order(created_at: :desc)
    @job = Job.new
  end

  def new
    @job = Job.new
  end

  def create
    @job = Job.new(job_params)

    respond_to do |format|
      if @job.save
        format.html { redirect_to jobs_path, notice: 'job was successfully created.' }
        format.json { render json: @job, status: :created }
        format.js   {}
      else
        format.html { render "new" }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    @job = Job.find(params[:id])
  end

  def edit
    @job = Job.find(params[:id])
  end

  def update
    @job = Job.find(params[:id])

    @job.update(job_params) ? (redirect_to root_path) : (render 'edit')
  end

  def destroy
    @job = Job.find(params[:id])
    redirect_to root_path if @job.destroy
  end

  private
  def job_params
    params.require(:job).permit(:company_name, :link, :job_title, :location, :status, :note, :contact_email, :intrigue_level)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/jobs/_form.html.erb
<div class="container">
<% modal ||= false %>
<% remote = modal ? true : false %>
<%= form_for(@job, remote: remote, html: {role: :form, 'data-model' => 'job'}) do |f| %>
  <% if @job.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@job.errors.count, "error") %> prohibited this job from being saved: </h2>
    <ul>
      <% @job.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

  <div class="form-group">
    <span class="help-block"></span>
    <%= f.label :company_name, class: "control-label" %>
    <%= f.text_field :company_name, class: "form-control" %>
    <span class="help-block"></span>
  </div>

  <div class="form-group">
    <%= f.label :link, class: 'control-label' %>
    <%= f.text_field :link, class: "form-control" %>
    <span class="help-block"></span>
  </div>

  <div class="form-group">
    <%= f.label :job_title, class: 'control-label' %>
    <%= f.text_field :job_title, class: "form-control"%>
    <span class="help-block"></span>
  </div>

  <div class="form-group">
    <%= f.label :location, class: 'control-label' %>
    <%= f.text_field :location, class: "form-control" %>
    <span class="help-block"></span>
  </div>

  <div class="form-group">
    <%= f.label :status, class: 'control-label' %>
    <%= f.select :status, options_for_select(["Haven't Applied Yet", "In Process", "Applied/Contacted", "Didn't Work Out", "Dead Track", "Have a Connection", "When Desperate", "Sent Follow Up"]) %>
    <span class="help-block"></span>
  </div>

  <div class="form-group">
    <%= f.label :notes, class: 'control-label' %>
    <%= f.text_area :note, class: "form-control" %>
    <span class="help-block"></span>
  </div>

  <div class="form-group">
    <%= f.label :contact_email, class: 'control-label' %>
    <%= f.text_field :contact_email, class: "form-control" %>
    <span class="help-block"></span>
  </div>

  <div class="form-group">
    <%= f.label :intrigue_level, class: 'control-label' %>
    <%= f.select :intrigue_level, options_for_select([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]) %>
    <span class="help-block"></span>
  </div>

  <div class="actions">
    <%= f.submit 'Submit', class: 'btn btn-default' %>
  </div>
<% end %>
</div>

app/views/jobs/_job.html.erb
<div class="col-xs-6 col-md-4 item box"><a href="/jobs/<%= @job.id %>"><div class="well text-center data-status="<%= @job.status %>""><%= @job.company_name %> <br><%= @job.job_title %> <br> <%= @job.location %> </div></a></div>

app/views/jobs/create.js.erb
$("<%= escape_javascript(render @job) %>").appendTo('#jobs');
$('#new_job_modal').modal_success();

app/views/jobs/edit.html.erb
<%= render 'form' %>

app/views/jobs/index.html.erb
<div class="container">
<nav class="navbar navbar-default" role="navigation">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
  </div>
  <a class="navbar-brand" href="#">WELCOME</a>
  <div class="navbar-collapse collapse">
    <ul class="nav navbar-nav navbar-left">
        <li class="tagline"><a href="#"><%= current_user.email %></a></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li class="tagline"><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
    </ul>
  </div>
</nav>
</div>

<div class="container">
    <div class="row options">
        <div class="col-md-4 text-center">Sort</div>
        <div class="col-md-4 text-center"><%= link_to content_tag(:i,nil, :class=>"fa fa-plus fa-2x"), new_job_path, "data-toggle" => "modal", "data-target" => "#new_job_modal", "title" => "Add a job" %> </div>
        <div class="modal fade" id="new_job_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              </div>
              <div class="modal-body">
                <%= render 'form', modal: true %>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
              </div>
            </div>
          </div>
        </div>
        <div class="col-md-4 text-center">Search</div>
    </div>
<% @jobs.each do |job| %>
    <div class="container_two">
        <div class="row-fluid jobs">
            <div class="col-xs-6 col-md-4 item box"><a href="/jobs/<%= job.id %>"><div class="well text-center data-status="<%=job.status %>""> <%= job.company_name %> <br><%= job.job_title %> <br> <%= job.location %> </div></a></div>
        </div>
    </div>
<% end %>

</div>

app/views/jobs/new.html.erb
<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>On The Grind</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

</body>
</html>

app/views/welcome/index.html.erb
<div class="container">
<div class="row">
    <div class="header">
        <div class="title">On the grind </div>
        <div class="tagline">organize your job search.</div>
    </div>
</div>

<div class="row">
    <%= link_to "Sign In", new_user_session_path %>
    <br>
    <%= link_to "Sign Up", new_user_registration_path %>
</div>

</div>